package com.highdev.breazelife.modules.document.controller;

import com.highdev.breazelife.modules.document.dto.request.GenerateCertificateRequest;
import com.highdev.breazelife.modules.document.dto.response.DocumentResponse;
import com.highdev.breazelife.modules.document.service.AffiliateDocumentService;
import com.highdev.breazelife.modules.document.service.AffiliateDocumentService.AffiliateData;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * BLIFE-04-02 / BLIFE-04-03 / BLIFE-04-04 / BLIFE-04-05
 *
 * Endpoints para generación y descarga de documentos PDF del afiliado.
 *
 * Todos los endpoints requieren rol AFFILIATE.
 * El affiliateId se extrae del JWT para que un afiliado no pueda
 * acceder a documentos de otro afiliado.
 *
 * Endpoints:
 *   GET  /api/v1/affiliates/documents                        → listar documentos
 *   POST /api/v1/affiliates/documents/certificate            → generar certificado
 *   GET  /api/v1/affiliates/documents/{document_id}/download → descargar PDF
 */
@RestController
@RequestMapping("/api/v1/affiliates/documents")
@RequiredArgsConstructor
@PreAuthorize("hasRole('AFFILIATE')")
@SecurityRequirement(name = "bearerAuth")
@Tag(name = "Affiliate Documents", description = "PDF document generation and download for affiliates")
public class AffiliateDocumentController {

    private final AffiliateDocumentService documentService;

    // TODO: inyectar AccountService y AffiliateService cuando los módulos 2 y 3
    //       estén listos para reemplazar los datos mock de buildAffiliateData().

    // ── GET /api/v1/affiliates/documents ──────────────────────────────────────

    @GetMapping
    @Operation(
        summary = "List affiliate documents",
        description = "Returns all PDF documents previously generated by the authenticated affiliate"
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "Documents listed successfully"),
        @ApiResponse(responseCode = "401", description = "Unauthorized — missing or invalid token"),
        @ApiResponse(responseCode = "403", description = "Forbidden — user is not an affiliate")
    })
    public ResponseEntity<Map<String, Object>> getDocuments(
        @AuthenticationPrincipal UserDetails userDetails) {

        String affiliateId = extractAffiliateId(userDetails);
        List<DocumentResponse> documents = documentService.getDocuments(affiliateId);

        return ResponseEntity.ok(Map.of(
            "message", "Documents retrieved successfully",
            "status_code", 200,
            "status", "OK",
            "data", Map.of("items", documents)
        ));
    }

    // ── POST /api/v1/affiliates/documents/certificate ─────────────────────────

    @PostMapping("/certificate")
    @Operation(
        summary = "Generate affiliate certificate",
        description = "Generates an affiliation certificate, balance certificate, or account statement PDF. " +
            "fromDate and toDate are required only for ACCOUNT_STATEMENT type."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "201", description = "Certificate generated successfully"),
        @ApiResponse(responseCode = "400", description = "Invalid request — missing type or invalid date range"),
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    public ResponseEntity<Map<String, Object>> generateCertificate(
        @AuthenticationPrincipal UserDetails userDetails,
        @Valid @RequestBody GenerateCertificateRequest request) {

        String affiliateId = extractAffiliateId(userDetails);

        // Obtener datos del afiliado para construir el PDF
        // TODO: reemplazar buildAffiliateData() con llamadas reales a los services
        //       de los módulos 2 y 3 cuando estén integrados.
        AffiliateData data = buildAffiliateData(affiliateId);

        DocumentResponse result = documentService.generateCertificate(
            affiliateId, request, data);

        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of(
            "message", "Certificate generated successfully",
            "status_code", 201,
            "status", "CREATED",
            "data", result
        ));
    }

    // ── GET /api/v1/affiliates/documents/{document_id}/download ──────────────

    @GetMapping("/{document_id}/download")
    @Operation(
        summary = "Download affiliate document PDF",
        description = "Returns the binary PDF file for the requested document. " +
            "Only the owner affiliate can download their documents."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "PDF returned successfully"),
        @ApiResponse(responseCode = "404", description = "Document not found"),
        @ApiResponse(responseCode = "403", description = "Forbidden — document belongs to another affiliate")
    })
    public ResponseEntity<byte[]> downloadDocument(
        @AuthenticationPrincipal UserDetails userDetails,
        @PathVariable("document_id") String documentId) {

        String affiliateId = extractAffiliateId(userDetails);
        byte[] pdfBytes    = documentService.downloadDocument(documentId, affiliateId);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_PDF);
        headers.setContentDispositionFormData("attachment", documentId + ".pdf");
        headers.setContentLength(pdfBytes.length);

        return ResponseEntity.ok().headers(headers).body(pdfBytes);
    }

    // ── Helpers privados ──────────────────────────────────────────────────────

    /**
     * Extrae el affiliateId del JWT autenticado.
     * TODO: ajustar cuando el módulo 1 defina cómo almacena el userId en UserDetails.
     */
    private String extractAffiliateId(UserDetails userDetails) {
        return userDetails.getUsername();
    }

    /**
     * Construye los datos del afiliado para el PDF.
     *
     * MOCK — reemplazar con llamadas reales:
     *   - affiliateService.getByUserId(affiliateId)  → nombre, cédula, fechas
     *   - accountService.getByAffiliateId(affiliateId) → balance, quotedDays, accountType
     *   - quoteService.getAccepted(affiliateId)      → lista de cotizaciones
     *   - profitabilityService.getByAffiliate(affiliateId) → rentabilidades
     */
    private AffiliateData buildAffiliateData(String affiliateId) {
        return new AffiliateData(
            "Laura",
            "Gómez",
            "1002456789",
            LocalDate.of(1995, 3, 15),
            LocalDate.of(2024, 1, 10),
            "MODERATE",
            4500000.0,
            210,
            List.of(),
            List.of()
        );
    }
}