package com.highdev.breazelife.modules.document.controller;

import com.highdev.breazelife.modules.document.dto.request.GenerateCertificateRequest;
import com.highdev.breazelife.modules.document.dto.response.DocumentResponse;
import com.highdev.breazelife.modules.document.service.AffiliateDocumentService;
import com.highdev.breazelife.modules.document.service.AffiliateDocumentService.AffiliateData;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/affiliates/documents")
@RequiredArgsConstructor
@Tag(name = "Affiliate Documents", description = "PDF document generation and download for affiliates")
public class AffiliateDocumentController {

    private final AffiliateDocumentService documentService;

    // ── GET /api/v1/affiliates/documents ──────────────────────────────────────

    @GetMapping
    @Operation(
        summary = "List affiliate documents",
        description = "Returns all PDF documents previously generated by the authenticated affiliate"
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "Documents listed successfully"),
        @ApiResponse(responseCode = "401", description = "Unauthorized — missing or invalid token"),
        @ApiResponse(responseCode = "403", description = "Forbidden — user is not an affiliate")
    })
    public ResponseEntity<Map<String, Object>> getDocuments(
        @AuthenticationPrincipal UserDetails userDetails) {

        String affiliateId = extractAffiliateId(userDetails);
        List<DocumentResponse> documents = documentService.getDocuments(affiliateId);

        return ResponseEntity.ok(Map.of(
            "message", "Documents retrieved successfully",
            "status_code", 200,
            "status", "OK",
            "data", Map.of("items", documents)
        ));
    }

    // ── POST /api/v1/affiliates/documents/certificate ─────────────────────────

    @PostMapping("/certificate")
    @Operation(
        summary = "Generate affiliate certificate",
        description = "Generates an affiliation certificate, balance certificate, or account statement PDF. " +
            "fromDate and toDate are required only for ACCOUNT_STATEMENT type."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "201", description = "Certificate generated successfully"),
        @ApiResponse(responseCode = "400", description = "Invalid request — missing type or invalid date range"),
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        @ApiResponse(responseCode = "403", description = "Forbidden")
    })
    public ResponseEntity<Map<String, Object>> generateCertificate(
        @AuthenticationPrincipal UserDetails userDetails,
        @Valid @RequestBody GenerateCertificateRequest request) {

        String affiliateId = extractAffiliateId(userDetails);
        AffiliateData data = buildAffiliateData(affiliateId);

        DocumentResponse result = documentService.generateCertificate(
            affiliateId, request, data);

        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of(
            "message", "Certificate generated successfully",
            "status_code", 201,
            "status", "CREATED",
            "data", result
        ));
    }

    // ── GET /api/v1/affiliates/documents/{document_id}/download ──────────────

    @GetMapping("/{document_id}/download")
    @Operation(
        summary = "Download affiliate document PDF",
        description = "Returns the binary PDF file for the requested document."
    )
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "PDF returned successfully"),
        @ApiResponse(responseCode = "404", description = "Document not found"),
        @ApiResponse(responseCode = "403", description = "Forbidden — document belongs to another affiliate")
    })
    public ResponseEntity<byte[]> downloadDocument(
        @AuthenticationPrincipal UserDetails userDetails,
        @PathVariable("document_id") String documentId) {

        String affiliateId = extractAffiliateId(userDetails);
        byte[] pdfBytes    = documentService.downloadDocument(documentId, affiliateId);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_PDF);
        headers.setContentDispositionFormData("attachment", documentId + ".pdf");
        headers.setContentLength(pdfBytes.length);

        return ResponseEntity.ok().headers(headers).body(pdfBytes);
    }

    // ── Helpers privados ──────────────────────────────────────────────────────

    /**
     * Extrae el affiliateId del JWT.
     * Si no hay usuario autenticado (modo desarrollo sin JWT),
     * retorna un ID de prueba.
     * TODO: remover el fallback cuando módulo 1 esté integrado.
     */
    private String extractAffiliateId(UserDetails userDetails) {
        if (userDetails == null) {
            return "test-affiliate-id";
        }
        return userDetails.getUsername();
    }

    /**
     * MOCK de datos del afiliado.
     * TODO: reemplazar con llamadas reales cuando módulos 2 y 3 estén listos:
     *   - affiliateService.getByUserId(affiliateId)
     *   - accountService.getByAffiliateId(affiliateId)
     *   - quoteService.getAccepted(affiliateId)
     *   - profitabilityService.getByAffiliate(affiliateId)
     */
    private AffiliateData buildAffiliateData(String affiliateId) {
        return new AffiliateData(
            "Laura",
            "Gómez",
            "1002456789",
            LocalDate.of(1995, 3, 15),
            LocalDate.of(2024, 1, 10),
            "MODERATE",
            4500000.0,
            210,
            List.of(),
            List.of()
        );
    }
}